name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# Release version: v4.0.0 (Do not change this line)
# A version number is three numbers separated by dots, like 1.2.43 - followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion. Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3000

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  inspireui: 2.0.0

  flutterflow:
    path: packages/flutterflow/
  flux_firebase:
    path: packages/flux_firebase/

  # Base
  flutter_localization: ^0.2.0
  intl: any
  crypto: 3.0.3
  path_provider: 2.1.2
  url_launcher: 6.2.5
  flutter_secure_storage: 9.0.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: ^1.1.0
  dio: ^5.2.1
  http_auth: 1.0.4
  share: 2.0.4
  tuple: 2.0.2
  collection: any
  quiver: 3.2.1
  async: 2.11.0
  html: 0.15.4
  vector_math: 2.1.4
  path: 1.9.0
  flutter_svg: 2.0.10+1
  notification_permissions: 0.6.1
  flutter_local_notifications: 14.1.5
  onesignal_flutter: 5.1.0
  new_version_plus: 0.0.11

  # STATE MANAGEMENT
  provider: 6.0.5
  get_it: 7.6.7

  # SPLASH SCREEN, ONBOARD
  lottie: 3.1.0
  rive: 0.12.4

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 4.2.2
  webview_flutter_web: 0.2.2+4
  responsive_builder: 0.7.0
  flutter_inappwebview: 5.8.0

  # HTML render
  flutter_widget_from_html_core: 0.14.11
  fwfh_svg: 0.8.1
  fwfh_cached_network_image: 0.14.2
  fwfh_url_launcher: 0.9.0+4
  #  fwfh_chewie: 0.7.1+2 # accentColor issue
  fwfh_webview: 0.14.8

  # VIDEO
  video_player: 2.8.2
  youtube_player_iframe:
    git:
      url: https://github.com/inspireui/youtube_player_flutter.git
      path: packages/youtube_player_iframe
      ref: c2268281ca7f1f051f7ccab373e982d22c540910

  # MAP
  google_maps_flutter: 2.5.3
  location: 5.0.3
  geocoding: 2.2.0

  # AUTHENTICATION
  local_auth: 2.2.0
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 6.1.1
  google_sign_in: 6.2.1
  sms_autofill: 2.3.1
  permission_handler: 11.3.0

  # FILES, IMAGES
  file_picker: 6.1.1
  cached_network_image: 3.3.1
  image: 4.1.7
  transparent_image: 2.0.1
  image_picker: 1.0.7
  flutter_native_image: 0.0.6+1
  flutter_cache_manager: 3.3.1
  wechat_assets_picker: 9.0.0
  photo_manager: 3.0.0

  # TOOLS
  google_fonts: 6.1.0
  random_string: 2.3.1
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  timeago: 3.6.1
  universal_platform: 1.0.0+1
  uuid: 4.3.3
  easy_debounce: 2.0.3
  devicelocale: 0.7.0
  visibility_detector: 0.4.0+2
  rate_my_app: 2.0.0
  flutter_linkify: 6.0.0
  gms_check: 1.0.2
  google_mobile_ads: 4.0.0
  speech_to_text: 6.6.0 # block by qr_code_scanner
  flutter_keyboard_visibility: 6.0.0
  app_tracking_transparency: 2.0.4

  # UI
  flutter_spinkit: 5.2.0
  smooth_page_indicator: 1.1.0
  animated_text_kit: 4.2.2
  flash: 3.1.0
  flutter_staggered_grid_view: 0.7.0
  pin_code_fields: 8.0.1
  country_pickers: 2.0.0
  dropdown_search: 5.0.6
  intro_slider: 4.2.1
  extended_image: 8.2.0
  dotted_decoration: 2.0.0
  awesome_card: 1.1.7
  qr_code_scanner: 1.0.1
  flutter_calendar_carousel: 2.4.2 # use intl 0.18.0
  sticky_headers: 0.3.0+2
  jumping_dot: 0.0.6
  fl_chart: 0.66.2
  tiktoklikescroller: 0.2.6
  readmore: 2.2.0
  flutter_animate: 4.5.0
  flutter_async_autocomplete: 0.1.1
  scrollable_positioned_list: 0.3.8
  country_code_picker: 3.0.0
  carousel_slider: 4.2.1
  rect_getter: 1.1.0
  scroll_to_index: 3.0.1
  flutter_zoom_drawer: 3.2.0
  infinite_carousel: 1.1.1
  timezone: 0.9.2
  sliver_tools: ^0.2.12
  flutter_staggered_animations: 1.1.1

  ### Native Payment
  razorpay_flutter:
    git:
      url: https://github.com/inspireui/razorpay-flutter
      ref: b5b7f1497e9581aadb60cdd00824e8a5747bb03a
  paytm_allinonesdk: # Fix conflict return callback url with stripe
    git:
      url: https://github.com/inspireui/paytm_allinonesdk.git
      ref: c885ad07605d7ba012c8daec443bb7ed9873e798
  pay_with_paystack:
    git:
      url: https://github.com/inspireui/pay_with_paystack
      ref: fb5141964b99deb463789433be9ba923770bf58c
  flutter_paystack:
    git:
      url: https://github.com/inspireui/flutter_paystack
      ref: a2f084e96998135ba2f05165887d0750f79852c8
  flutterwave_standard: 1.0.8

  #### For Shopify GraphQL
  graphql: 5.2.0-beta.7

  ### Flutter 3 fix warning
  intl_phone_number_input: # custom feature for phone number
    git:
      url: https://github.com/inspireui/intl_phone_number_input
      ref: 1a3fa368a009eac3cf02a91052956981da10e725
  flutter_swiper_null_safety:
    git:
      url: https://github.com/inspireui/flutter_swiper_null_safety
      ref: 18e8d2d642ff9e0013fc4477c6d64c52732b463a
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter
  pull_to_refresh:
    git:
      url: https://github.com/inspireui/flutter_pull_to_refresh
      ref: 24df296e282cd8b4ea8d3a5e171f4156a0295d1b
  multiple_localization:
    git:
      url: https://github.com/inspireui/flutter_multiple_localization
      ref: 48b65fa88ed468331d56ee86a102d808596c0a50

  ###---- Some extra feature is disable by default -----###
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.1

  ### â¬‡ï¸ Enable In App Update on Android feature
  ### Uncomment file lib/common/tools/in_app_update_for_android.dart
  in_app_update: 4.2.2
  meta_seo: 3.0.9

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_native_splash: 2.3.10
  build_runner: 2.4.8
  freezed: 2.4.7
  json_serializable: 6.7.1

### Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: 3.2.2  # pub run dependency_validator

### Enable Generate Icon library
  flutter_launcher_icons: 0.13.1

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - lib/config/us_store/
    - lib/config/vi_store/
    - assets/icons/brands/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/map_styles/
    - assets/html/
    - google_fonts/

### Uncomment to use custom font
#  fonts:
#    - family: Your Custom Font
#      fonts:
#      - asset: google_fonts/GE-Hili-Book.ttf

flutter_intl:
  enabled: true
  use_deferred_loading: true
